name: cicd

on:
  push:
    branches:
      - v3.2.1-openmldb
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build_spark_distribution:
    runs-on: macos-latest
      - name: compile
        run: |
          ./dev/make-distribution.sh --name openmldbspark --tgz -Phadoop-2.7 -Pyarn -Pkubernetes

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            spark-*-bin-openmldbspark.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
